@subscriptionId = 9e7d5c01-90ea-4969-bdbf-a4517cd82ccd

@resourceGroup = aadk8test

@provider = microsoft.extendedlocation

@apiVersion = 2020-07-15-privatepreview

@reqParams = ?api-version={{apiVersion}}

@customLocationName = cl-{{uni}}

@connectedClusterName = onboard-kubeadm-vmm-we-01

@hostResourceId = /subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroup}}/providers/Microsoft.Kubernetes/connectedClusters/{{connectedClusterName}}

@namespace = ns-{{uni}}

@clusterExtensionId = {{hostResourceId}}/providers/Microsoft.KubernetesConfiguration/extensions/azure-vmmoperator

@location = westeurope

@cls = {{armRoot}}/subscriptions/{{subscriptionId}}/resourcegroups/{{resourceGroup}}/providers/{{provider}}/customlocations
###
PUT {{cls}}/{{customLocationName}}{{reqParams}}
Content-Type: application/json

<@ ./payload/customLocation.json

###
DELETE {{cls}}/{{customLocationName}}{{reqParams}}

### 
# @name clGet
GET {{cls}}/{{customLocationName}}{{reqParams}}

###
# @name clHost
GET {{armRoot}}{{clGet.response.body.properties.hostResourceId}}?api-version=2020-01-01-preview

###
# @name clExt
GET {{armRoot}}{{clGet.response.body.properties.clusterExtensionIds[0]}}?api-version=2020-07-01-preview
