@subscriptionId = 204898ee-cd13-4332-b9d4-55ca5c25496d

@apiVersion = 2020-06-01

@reqParams = ?api-version={{apiVersion}}

@resourceGroupName = snaskar-rg

@location = eastus

@rg = {{armRoot}}/subscriptions/{{subscriptionId}}/resourcegroups/{{resourceGroupName}}?api-version={{apiVersion}}
###
PUT {{rg}}
Content-Type: application/json

{
	"location": "{{location}}"
}
###
DELETE {{rg}}
###
GET {{rg}}
