@subscriptionId = 70aad6c5-69f0-4905-87b8-f8700e08e2dd
@resourceGroup = snaskar-rg
@provider = Microsoft.SCVMM
@armStub = subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroup}}/providers/{{provider}}
@reqParams = ?api-version=2020-06-05-preview
@extendedLocName = /subscriptions/9e7d5c01-90ea-4969-bdbf-a4517cd82ccd/resourcegroups/aadk8test/providers/microsoft.extendedlocation/customlocations/cl-{{uni}}

@location = westeurope

#------------------------------------------------------------------------------------------------
### Create all resources
# -------------------------------------------------------------------------------------------------
### VMMServer
# @name getAllVMMServer
GET {{armRoot}}/{{armStub}}/vmmServers{{reqParams}}
###
@vmmServerName = vmmserver-xmas
@vmmServerId = /{{armStub}}/vmmServers/{{vmmServerName}}
# @name vmmServerPut
PUT {{armRoot}}{{vmmServerId}}{{reqParams}}
Content-Type: application/json

<@ ./payload/vmmServer.json

###
# @name vmmServerPutAsyncGet
GET {{vmmServerPut.response.headers.Azure-AsyncOperation}}

###
# @name vmmServerGet
GET {{armRoot}}{{vmmServerId}}{{reqParams}}

# -------------------------------------------------------------------------------------------------
### Cloud
# @name getAllCloud
GET {{armRoot}}/{{armStub}}/clouds{{reqParams}}
### Cloud QoS
@cloudQosName = cloud-qos-{{uni}}
@cloudQosId = /{{armStub}}/clouds/{{cloudQosName}}
# @name cloudQosPut
PUT {{armRoot}}{{cloudQosId}}{{reqParams}}
Content-Type: application/json

<@ ./payload/cloud-qos.json

###
# @name cloudQosPutAsyncGet
GET {{cloudQosPut.response.headers.Azure-AsyncOperation}}

###
# @name cloudQosGet
GET {{armRoot}}{{cloudQosId}}{{reqParams}}

### Cloud no QoS
@cloudNoQosName = cloud-no-qos-{{uni}}
@cloudNoQosId = /{{armStub}}/clouds/{{cloudNoQosName}}
# @name cloudNoQosPut
PUT {{armRoot}}{{cloudNoQosId}}{{reqParams}}
Content-Type: application/json

<@ ./payload/cloud-no-qos.json

###
# @name cloudNoQosPutAsyncGet
GET {{cloudNoQosPut.response.headers.Azure-AsyncOperation}}

###
# @name cloudNoQosGet
GET {{armRoot}}{{cloudNoQosId}}{{reqParams}}

# -------------------------------------------------------------------------------------------------
### VirtualNetwork 1
# @name getAllVN
GET {{armRoot}}/{{armStub}}/virtualNetworks{{reqParams}}
###
@virtualNetwork1Name = vnet-561-{{uni}}

@virtualNetwork1Id = /{{armStub}}/virtualNetworks/{{virtualNetwork1Name}}
# @name virtualNetwork1Put
PUT {{armRoot}}{{virtualNetwork1Id}}{{reqParams}}
Content-Type: application/json

<@ ./payload/virtualNetwork-1.json

###
# @name virtualNetwork1PutAsyncGet
GET {{virtualNetwork1Put.response.headers.Azure-AsyncOperation}}

###
# @name virtualNetwork1Get
GET {{armRoot}}{{virtualNetwork1Id}}{{reqParams}}

# -------------------------------------------------------------------------------------------------
### VirtualNetwork 2
@virtualNetwork2Name = vnet-562-{{uni}}
@virtualNetwork2Id = /{{armStub}}/virtualNetworks/{{virtualNetwork2Name}}
# @name virtualNetwork2Put
PUT {{armRoot}}{{virtualNetwork2Id}}{{reqParams}}
Content-Type: application/json

<@ ./payload/virtualNetwork-2.json

###
# @name virtualNetwork2PutAsyncGet
GET {{virtualNetwork2Put.response.headers.Azure-AsyncOperation}}

###
# @name virtualNetwork2Get
GET {{armRoot}}{{virtualNetwork2Id}}{{reqParams}}

# -------------------------------------------------------------------------------------------------
### VirtualMachineTemplate
# @name getAllVMT
GET {{armRoot}}/{{armStub}}/virtualMachineTemplates{{reqParams}}
###
@virtualMachineTemplateNameBlank = vmtemplate-blank-{{uni}}
@virtualMachineTemplateIdBlank = /{{armStub}}/virtualMachineTemplates/{{virtualMachineTemplateNameBlank}}
# @name virtualMachineTemplatePutBlank
PUT {{armRoot}}{{virtualMachineTemplateIdBlank}}{{reqParams}}
Content-Type: application/json

<@ ./payload/vmTemplate-blank.json

###
# @name virtualMachineTemplatePutAsyncGetBlank
GET {{virtualMachineTemplatePutBlank.response.headers.Azure-AsyncOperation}}

###
GET {{armRoot}}{{virtualMachineTemplateIdBlank}}{{reqParams}}
###

@virtualMachineTemplateNameLinux = vmtemplate-ubuntu-{{uni}}
@virtualMachineTemplateIdLinux = /{{armStub}}/virtualMachineTemplates/{{virtualMachineTemplateNameLinux}}
# @name virtualMachineTemplatePutLinux
PUT {{armRoot}}{{virtualMachineTemplateIdLinux}}{{reqParams}}
Content-Type: application/json

<@ ./payload/vmTemplate-linux.json

###
# @name virtualMachineTemplatePutAsyncGetLinux
GET {{virtualMachineTemplatePutLinux.response.headers.Azure-AsyncOperation}}

###
GET {{armRoot}}{{virtualMachineTemplateIdLinux}}{{reqParams}}

###
@virtualMachineTemplateNameWindows = vmtemplate-win-{{uni}}
@virtualMachineTemplateIdWindows = /{{armStub}}/virtualMachineTemplates/{{virtualMachineTemplateNameWindows}}
# @name virtualMachineTemplatePutWindows
PUT {{armRoot}}{{virtualMachineTemplateIdWindows}}{{reqParams}}
Content-Type: application/json

<@ ./payload/vmTemplate-windows.json

###

# @name virtualMachineTemplatePutAsyncGetWindows
GET {{virtualMachineTemplatePutWindows.response.headers.Azure-AsyncOperation}}

###
# @name virtualMachineTemplateGet
GET {{armRoot}}{{virtualMachineTemplateIdWindows}}{{reqParams}}

# -------------------------------------------------------------------------------------------------
### VirtualMachine
# @name getAllVM
GET {{armRoot}}/{{armStub}}/virtualMachines{{reqParams}}
###
@virtualMachineName = vm-insert-name-here
@virtualMachineId = /{{armStub}}/virtualMachines/{{virtualMachineName}}
# @name virtualMachinePut
PUT {{armRoot}}{{virtualMachineId}}{{reqParams}}
Content-Type: application/json

<@ ./payload/virtualMachine.json

###
# @name virtualMachinePutAsyncGet
GET {{virtualMachinePut.response.headers.Azure-AsyncOperation}}

###
# @name virtualMachineGet
GET {{armRoot}}{{virtualMachineId}}{{reqParams}}

### Actions
# @name startVM
POST {{armRoot}}{{virtualMachineId}}/start{{reqParams}}

###
# @name startVMAsyncGet
GET {{startVM.response.headers.Location}}

#------------------------------------------------------------------------------------------------
### Delete all resources
#------------------------------------------------------------------------------------------------
### VirtualMachine
# @name virtualMachineDel
DELETE {{armRoot}}{{virtualMachineId}}{{reqParams}}
###
# @name virtualMachineDelAsyncGet
GET {{virtualMachineDel.response.headers.Location}}

#------------------------------------------------------------------------------------------------
### VirtualMachineTemplate
# @name virtualMachineTemplateDel
DELETE {{armRoot}}{{virtualMachineTemplateIdBlank}}{{reqParams}}
###
# @name virtualMachineTemplateDelAsyncGet
GET {{virtualMachineTemplateDel.response.headers.Location}}

#------------------------------------------------------------------------------------------------
### VirtualNetwork 2
# @name virtualNetwork2Del
DELETE {{armRoot}}{{virtualNetwork2Id}}{{reqParams}}
###
# @name virtualNetwork2DelAsyncGet
GET {{virtualNetwork2Del.response.headers.Location}}

#------------------------------------------------------------------------------------------------
### VirtualNetwork 1
# @name virtualNetwork1Del
DELETE {{armRoot}}{{virtualNetwork1Id}}{{reqParams}}
###
# @name virtualNetwork1DelAsyncGet
GET {{virtualNetwork1Del.response.headers.Location}}

#------------------------------------------------------------------------------------------------
### CloudQos
# @name cloudQosDel
DELETE {{armRoot}}{{cloudQosId}}{{reqParams}}
###
# @name cloudQosDelAsyncGet
GET {{cloudQosDel.response.headers.Location}}

#------------------------------------------------------------------------------------------------
### CloudNoQos
# @name cloudNoQosDel
DELETE {{armRoot}}{{cloudNoQosId}}{{reqParams}}
###
# @name cloudNoQosDelAsyncGet
GET {{cloudNoQosDel.response.headers.Location}}

#------------------------------------------------------------------------------------------------
###
# @name vmmServerDel
DELETE {{armRoot}}{{vmmServerId}}{{reqParams}}
###
# @name vmmServerDelAsyncGet
GET {{vmmServerDel.response.headers.Location}}

#------------------------------------------------------------------------------------------------
###
