@armRoot = https://management.azure.com
@subscriptionId = 70aad6c5-69f0-4905-87b8-f8700e08e2dd
@resourceGroup = snaskar-test
@provider = Microsoft.SCVMM
@armStub = subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroup}}/providers/{{provider}}
@reqParams = ?api-version=2020-06-05-preview
@extendedLocName = /subscriptions/9e7d5c01-90ea-4969-bdbf-a4517cd82ccd/resourcegroups/aadk8test/providers/microsoft.extendedlocation/customlocations/vmmcl002

#------------------------------------------------------------------------------------------------
### Create all resources
# -------------------------------------------------------------------------------------------------
### VMMServer
@vmmServerName = arc-vmmserver
@vmmServerId = /{{armStub}}/vmmServers/{{vmmServerName}}
# @name vmmServerPut
PUT {{armRoot}}{{vmmServerId}}{{reqParams}}
Content-Type: application/json

<@ ./payload/vmmServer.json

###
# @name vmmServerPutAsyncGet
GET {{vmmServerPut.response.headers.Azure-AsyncOperation}}

###
# @name vmmServerGet
GET {{armRoot}}{{vmmServerId}}{{reqParams}}

# -------------------------------------------------------------------------------------------------
### Cloud
@cloudName = arc-cloud
@cloudId = /{{armStub}}/clouds/{{cloudName}}
# @name cloudPut
PUT {{armRoot}}{{cloudId}}{{reqParams}}
Content-Type: application/json

<@ ./payload/cloud.json

###
# @name cloudPutAsyncGet
GET {{cloudPut.response.headers.Azure-AsyncOperation}}

###
# @name cloudGet
GET {{armRoot}}{{cloudId}}{{reqParams}}

# -------------------------------------------------------------------------------------------------
### VirtualNetwork 1
@virtualNetwork1Name = arc-virtualnetwork-1
@virtualNetwork1Id = /{{armStub}}/virtualNetworks/{{virtualNetwork1Name}}
# @name virtualNetwork1Put
PUT {{armRoot}}{{virtualNetwork1Id}}{{reqParams}}
Content-Type: application/json

<@ ./payload/virtualNetwork-1.json

###
# @name virtualNetwork1PutAsyncGet
GET {{virtualNetwork1Put.response.headers.Azure-AsyncOperation}}

###
# @name virtualNetwork1Get
GET {{armRoot}}{{virtualNetwork1Id}}{{reqParams}}

# -------------------------------------------------------------------------------------------------
### VirtualNetwork 2
@virtualNetwork2Name = arc-virtualnetwork-2
@virtualNetwork2Id = /{{armStub}}/virtualNetworks/{{virtualNetwork2Name}}
# @name virtualNetwork2Put
PUT {{armRoot}}{{virtualNetwork2Id}}{{reqParams}}
Content-Type: application/json

<@ ./payload/virtualNetwork-2.json

###
# @name virtualNetwork2PutAsyncGet
GET {{virtualNetwork2Put.response.headers.Azure-AsyncOperation}}

###
# @name virtualNetwork2Get
GET {{armRoot}}{{virtualNetwork2Id}}{{reqParams}}

# -------------------------------------------------------------------------------------------------
### VirtualMachineTemplate
@virtualMachineTemplateName = arc-virtualMachineTemplate
@virtualMachineTemplateId = /{{armStub}}/virtualMachineTemplates/{{virtualMachineTemplateName}}
# @name virtualMachineTemplatePut
PUT {{armRoot}}{{virtualMachineTemplateId}}{{reqParams}}
Content-Type: application/json

<@ ./payload/virtualMachineTemplate.json

###
# @name virtualMachineTemplatePutAsyncGet
GET {{virtualMachineTemplatePut.response.headers.Azure-AsyncOperation}}

###
# @name virtualMachineTemplateGet
GET {{armRoot}}{{virtualMachineTemplateId}}{{reqParams}}

# -------------------------------------------------------------------------------------------------
### VirtualMachine
@virtualMachineName = arc-virtualMachine
@virtualMachineId = /{{armStub}}/virtualMachines/{{virtualMachineName}}
# @name virtualMachinePut
PUT {{armRoot}}{{virtualMachineId}}{{reqParams}}
Content-Type: application/json

<@ ./payload/virtualMachine.json

###
# @name virtualMachinePutAsyncGet
GET {{virtualMachinePut.response.headers.Azure-AsyncOperation}}

###
# @name virtualMachineGet
GET {{armRoot}}{{virtualMachineId}}{{reqParams}}

#------------------------------------------------------------------------------------------------
### Delete all resources
#------------------------------------------------------------------------------------------------
### VirtualMachine
# @name virtualMachineDel
DELETE {{armRoot}}{{virtualMachineId}}{{reqParams}}
###
# @name virtualMachineDelAsyncGet
GET {{virtualMachineDel.response.headers.Location}}

#------------------------------------------------------------------------------------------------
### VirtualMachineTemplate
# @name virtualMachineTemplateDel
DELETE {{armRoot}}{{virtualMachineTemplateId}}{{reqParams}}
###
# @name virtualMachineTemplateDelAsyncGet
GET {{virtualMachineTemplateDel.response.headers.Location}}

#------------------------------------------------------------------------------------------------
### VirtualNetwork 2
# @name virtualNetwork2Del
DELETE {{armRoot}}{{virtualNetwork2Id}}{{reqParams}}
###
# @name virtualNetwork2DelAsyncGet
GET {{virtualNetwork2Del.response.headers.Location}}

#------------------------------------------------------------------------------------------------
### VirtualNetwork 1
# @name virtualNetwork1Del
DELETE {{armRoot}}{{virtualNetwork1Id}}{{reqParams}}
###
# @name virtualNetwork1DelAsyncGet
GET {{virtualNetwork1Del.response.headers.Location}}

#------------------------------------------------------------------------------------------------
### Cloud
# @name cloudDel
DELETE {{armRoot}}{{cloudId}}{{reqParams}}
###
# @name cloudDelAsyncGet
GET {{cloudDel.response.headers.Location}}

#------------------------------------------------------------------------------------------------
###
# @name vmmServerDel
DELETE {{armRoot}}{{vmmServerId}}{{reqParams}}
###
# @name vmmServerDelAsyncGet
GET {{vmmServerDel.response.headers.Location}}

#------------------------------------------------------------------------------------------------